[package]
name = "steam-shovel"
version = "0.1.0"
authors = ["Saghm Rossi <saghmrossi@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "MTG mulligan helper"

[dependencies]
structopt = "0.2.14"
